// <auto-generated />
using System;
using Attic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Attic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AtticDbContext))]
    [Migration("20260422074009_SchemaHardening")]
    partial class SchemaHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attic.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("comment");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("StoragePath")
                        .HasDatabaseName("ix_attachments_storage_path");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_attachments_uploader_id");

                    b.HasIndex("MessageId", "CreatedAt")
                        .HasDatabaseName("ix_attachments_message_created");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid?>("TargetChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_channel_id");

                    b.Property<long?>("TargetMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_message_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created");

                    b.HasIndex("TargetChannelId")
                        .HasDatabaseName("ix_audit_logs_target_channel");

                    b.HasIndex("TargetMessageId")
                        .HasDatabaseName("ix_audit_logs_target_message")
                        .HasFilter("target_message_id IS NOT NULL");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_audit_logs_target_user")
                        .HasFilter("target_user_id IS NOT NULL");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_channels_name_not_personal")
                        .HasFilter("kind <> 2 AND deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Description", "Kind" });

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_channels_owner")
                        .HasFilter("owner_id IS NOT NULL");

                    b.ToTable("channels", null, t =>
                        {
                            t.HasCheckConstraint("ck_channels_kind_enum", "kind IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitee_id");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channel_invitations");

                    b.HasIndex("InviterId")
                        .HasDatabaseName("ix_channel_invitations_inviter_id");

                    b.HasIndex("ChannelId", "InviteeId")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_invitations_channel_invitee_pending")
                        .HasFilter("status = 0");

                    b.HasIndex("InviteeId", "Status")
                        .HasDatabaseName("ix_channel_invitations_invitee_status");

                    b.ToTable("channel_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_channel_invitations_status_enum", "status IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelMember", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid?>("BannedById")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChannelId", "UserId")
                        .HasName("pk_channel_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_channel_members_user");

                    b.ToTable("channel_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_channel_members_role_enum", "role IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelRead", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("LastReadMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_message_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChannelId", "UserId")
                        .HasName("pk_channel_reads");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_channel_reads_user");

                    b.ToTable("channel_reads", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_friend_requests");

                    b.HasIndex("RecipientId", "Status")
                        .HasDatabaseName("ix_friend_requests_recipient_status");

                    b.HasIndex("SenderId", "RecipientId")
                        .IsUnique()
                        .HasDatabaseName("ux_friend_requests_sender_recipient_pending")
                        .HasFilter("status = 0");

                    b.ToTable("friend_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_friend_requests_status_enum", "status IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserAId", "UserBId")
                        .HasName("pk_friendships");

                    b.HasIndex("UserAId")
                        .HasDatabaseName("ix_friendships_user_a");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_friendships_user_b");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("ck_friendships_user_order", "user_a_id < user_b_id");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("ReplyToId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ReplyToId")
                        .HasDatabaseName("ix_messages_reply_to_id");

                    b.HasIndex("ChannelId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_channel_id_desc");

                    b.HasIndex("SenderId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_sender_id_desc");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_messages_content_length", "octet_length(content) <= 3072");
                        });
                });

            modelBuilder.Entity("Attic.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("BlockerId", "BlockedId")
                        .HasName("pk_user_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_user_blocks_blocked");

                    b.ToTable("user_blocks", (string)null);
                });

            modelBuilder.Entity("Attic.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Attic.Domain.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attachments_message");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_uploader");
                });

            modelBuilder.Entity("Attic.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_actor");
                });

            modelBuilder.Entity("Attic.Domain.Entities.Channel", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_channels_owner");
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelInvitation", b =>
                {
                    b.HasOne("Attic.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_invitations_channel");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_channel_invitations_invitee");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_channel_invitations_inviter");
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelMember", b =>
                {
                    b.HasOne("Attic.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_members_channel");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_channel_members_user");
                });

            modelBuilder.Entity("Attic.Domain.Entities.ChannelRead", b =>
                {
                    b.HasOne("Attic.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_reads_channel");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_reads_user");
                });

            modelBuilder.Entity("Attic.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_recipient");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_sender");
                });

            modelBuilder.Entity("Attic.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_user_a");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_user_b");
                });

            modelBuilder.Entity("Attic.Domain.Entities.Message", b =>
                {
                    b.HasOne("Attic.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_channel");

                    b.HasOne("Attic.Domain.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_messages_reply_to");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sender");
                });

            modelBuilder.Entity("Attic.Domain.Entities.Session", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_user");
                });

            modelBuilder.Entity("Attic.Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_blocks_blocked");

                    b.HasOne("Attic.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_blocks_blocker");
                });
#pragma warning restore 612, 618
        }
    }
}
